### ISSUE TITLE
the problems about MCP3424

### ISSUE THREAD

**Issue by jiaran1031** [stevemarple/MCP342x#1]
Dear Mr Steve,
hello! I am a student from China, nice to meet you. could I ask you any questions about MCP3424?
I designed a circuit by using arduino due and MCP3424, and I used the sketches MCP342x _ListDevices to find the address of MCP3424,  but it failed, in the serial window, it showed 
"The MCP3422 and MCP3426 use I2C address 0x68, all other devices can be configured to use any address in the range 0x68 - 0x6F (inclusive).Be aware that the DS1307 uses address 0x68.
TWI_StartRead
Exiting with status 1." There is no address print out. 
Actually, in my circuit, the pin of MCP3424 ADR0 was connected AGND, ADR1 was connected VCC, so I changed the address 6E to 6A in the sketch convertAndRead, in the serial window, it showed "No device found at address 6A".
I don't know why MCP3424 can't communicate with arduino, could you help me? looking forward your reply.
yours,
Jia

**Comment by WickedDevice** [comment]
@jiaran1031 try this sketch https://github.com/RobTillaart/Arduino/tree/master/sketches/MultiSpeedI2CScanner to see if anything is found on the I2C bus at all. If nothing shows up, chances are you have a wiring problem, or you are missing external pull-up resistors which are required for I2C operation.

**Comment by stevemarple** [comment]
Can you post a circuit diagram showing how the MCP3424 and Arduino Due are connected? It seems like it may be a wiring problem if the MCP342x _ListDevices  sketch does not show anything. Are are you translating logic levels? The Arduino Due I2C pull-ups will be connected to 3.3V, since that is the voltage used by the ARM microcontroller. The MCP3424 is a 5V device and must be powered from 5V; normally it would expect the pull-ups to be connected to 5V. In cases like this where the supply voltages differ I always use a logic-level translation circuit. You might find that the MCP3424 will still work with the SDA and SCL pull-ups connected to 3.3V even when it is powered by 5V but it might not be reliable.

**Comment by howroyd** [comment]
The MCP3424 can be powered at 3V3

**Comment by stevemarple** [comment]
Device can be operated at 3.3V. No response from original poster so closing this issue.
